### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by KjellRS** [Xiaojiu-z/Stable-Hair#1]
I really like your paper and I think the two-step process of first making them bald, then applying the new hair style is brilliant. But I think there's a few things holding your model back from in-the-wild realism:

1. I think you have a horizontal flip in your image augmentations, causing it to create a similar but mirrored hairstyle. This happens in figure 10, rows 4 and 7 as well as columns 1, 2 and 7 in figure 13. Faces are symmetric but for asymmetric hairstyles left/right side matters. This is probably just commenting out one line and retraining.
2. If you look at the images mixed in the top left corner of figure 11, it looks quite bad. There's two reasons for this. One is the pose, in the reference image she's looking slightly to the right while the target image is looking slightly to the left. Despite this difference in pose the hair looks copy-pasted on in exactly the same shape. Particularly the edge of the ear sticking out is very unnatural and jarring.
3. The other problem is the lighting, in the reference image the sun is shining brightly on the subject's nose and upper lip while the source photo has neutral ambient lighting. This is also very obvious in figure 12, row 1 where the harsh sunlight of the source photo is not reflected at all in the new hairstyles.

I feel like I've seen solutions to 2) and 3) before, I don't know if you want to incorporate them in your model or as a preprocessing step. But I think if you make the images pose-aligned and harmonized lighting first, then applied your method you'll have great results because in the cases where they already have the same pose and lighting it already looks great.

**Comment by Xiaojiu-z** [comment]
> I really like your paper and I think the two-step process of first making them bald, then applying the new hair style is brilliant. But I think there's a few things holding your model back from in-the-wild realism:
> 
> 1. I think you have a horizontal flip in your image augmentations, causing it to create a similar but mirrored hairstyle. This happens in figure 10, rows 4 and 7 as well as columns 1, 2 and 7 in figure 13. Faces are symmetric but for asymmetric hairstyles left/right side matters. This is probably just commenting out one line and retraining.
> 2. If you look at the images mixed in the top left corner of figure 11, it looks quite bad. There's two reasons for this. One is the pose, in the reference image she's looking slightly to the right while the target image is looking slightly to the left. Despite this difference in pose the hair looks copy-pasted on in exactly the same shape. Particularly the edge of the ear sticking out is very unnatural and jarring.
> 3. The other problem is the lighting, in the reference image the sun is shining brightly on the subject's nose and upper lip while the source photo has neutral ambient lighting. This is also very obvious in figure 12, row 1 where the harsh sunlight of the source photo is not reflected at all in the new hairstyles.
> 
> I feel like I've seen solutions to 2) and 3) before, I don't know if you want to incorporate them in your model or as a preprocessing step. But I think if you make the images pose-aligned and harmonized lighting first, then applied your method you'll have great results because in the cases where they already have the same pose and lighting it already looks great.

Hi, thanks for your advice. I think the horizontal flip of hair may not be that important because if I horizontally flip the reference image input, I can easily get another output. As for 2 and 3, I will improve as per your suggestions and please look forward to my update~

**Comment by Xiaojiu-z** [comment]
Once again, I sincerely thank you for your advice～～

**Comment by YacratesWyh** [comment]
Using IC-light with a 0.5 grey image would be nice for getting an ambient sunlight, though it still leaves color bias.
