### ISSUE TITLE
How to get good outputs for long hair..?

### ISSUE THREAD

**Issue by sahilshukla3003** [Xiaojiu-z/Stable-Hair#12]
Great work ! But still one big challenge is changing the hairstyles for long hairs like in females , What if I want to use long hairs for styling , is there anyway for this... (retraining can help..? ) 

![Screenshot from 2024-10-30 18-08-48](https://github.com/user-attachments/assets/7faaad9a-74fb-4f6b-a5d6-9a23c2d0497c)

**Comment by Xiaojiu-z** [comment]
If you can acquire long hair datasets, maybe fine-tuning the model can help you solve this problem. (Just follow the technical report's instructions to make datasets and train stage2).

**Comment by sahilshukla3003** [comment]
> If you can acquire long hair datasets, maybe fine-tuning the model can help you solve this problem. (Just follow the technical report's instructions to make datasets and train stage2).

Can you please guide how to prepare the dataset in correct format , is source image and referenced image sufficient or do I also need ground truth images ...?
