### ISSUE TITLE
ID 人像合成发型的结果不太贴合，甚至生硬，应该从哪方面入手调整呢

### ISSUE THREAD

**Issue by lyggyhmm** [Xiaojiu-z/Stable-Hair#14]
<img width="783" alt="demo1" src="https://github.com/user-attachments/assets/7fb492be-3a14-4cf8-a170-88a070e26f23">
<img width="498" alt="demo2" src="https://github.com/user-attachments/assets/06005f6a-f114-4d53-bff7-2337b33a077b">
<img width="738" alt="demo3" src="https://github.com/user-attachments/assets/01b9895e-06ec-46eb-9492-4a5056a8743e">
@Xiaojiu-z 
你好，我成功运行了项目，并进行了几个试验
发现作者给的demo Id 图片的人像在合成效果上贴合度很高
但是更换ID 人脸后效果较差，我应该从哪方面入手进行优化呢，期待回复~

**Comment by lyggyhmm** [comment]
> 你好👋，limitation已在主页更新，Good case的ID图一般符合FFHQ数据集的特征，简单裁剪即可，不需要完全对齐。另外，如果需要训练效果更好的model，你需要做的事应该是爬一些高质量数据微调这个模型。

十分感谢！！

**Comment by lyggyhmm** [comment]
你好，如果我想对模型进行微调，是否有更低代价的方式进行训练，目前我仅有的资源是一张4090 24G的显卡，相较于arxiv中提到的H800显得力不从心哈哈哈。我还没有尝试进行训练，想问下是否会出现OOM的情况，或者其他的一些注意事项，期待回复~

**Comment by Xiaojiu-z** [comment]
> 你好，如果我想对模型进行微调，是否有更低代价的方式进行训练，目前我仅有的资源是一张4090 24G的显卡，相较于arxiv中提到的H800显得力不从心哈哈哈。我还没有尝试进行训练，想问下是否会出现OOM的情况，或者其他的一些注意事项，期待回复~

我觉得会出现OOM，你可能需要40G的A100
