### ISSUE TITLE
How much video memory needed for inference?

### ISSUE THREAD

**Issue by crankyz** [Xiaojiu-z/Stable-Hair#15]
Me dropped with 3060 12Gb with OOM error.

**Comment by Xiaojiu-z** [comment]
As I know, 24G is fine. I think you should use fp16/bf16/8bit/compile inference on 3060, but you need to change some code (btw, if you are done, may you help me update the code? )

**Comment by Yao-DY** [comment]
A portion of this question can be addressed: my graphics card is a 4070Ti, and I have tested the required memory size at different precisions. At float32 precision, 20GB is needed; at float16, 15GB is required. There are no lower quantization precisions available, as the model has requirements for floating-point or complex types, with the minimum being float16 or bfloat16.
