### ISSUE TITLE
无法安装依赖的nvidia-cudnn-cu11

### ISSUE THREAD

**Issue by Yao-DY** [Xiaojiu-z/Stable-Hair#21]
我使用的python版本为3.10.10，在使用requirements.txt安装依赖的时候，报错：
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu11==8.7.0.84 (from versions: 0.0.1.dev5, 8.9.4.25, 8.9.5.29, 9.0.0.312, 9.1.0.70, 9.1.1.17, 9.2.0.82, 9.2.1.18, 9.3.0.75, 9.4.0.58, 9.5.0.50, 9.5.1.17)
ERROR: No matching distribution found for nvidia-cudnn-cu11==8.7.0.84

在pypi上确实能看到这个版本，但pip install的时候找不到这个版本。

想问一下作者使用的python版本。如果是conda环境，能否提供yaml版本的环境配置？

**Comment by Xiaojiu-z** [comment]
torch版本不需要完全对应，重新安装一个最新版本的torch就行了：
# CUDA 11.8
pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu118
# CUDA 12.1
pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121
# CUDA 12.4
pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124
