### ISSUE TITLE
请问论文里光头效果和hairmapper效果图为何如此相似，都包含光头边界模糊效果，如何确保生成的光头不易畸变，期待作者的代码

### ISSUE THREAD

**Issue by 99012678** [Xiaojiu-z/Stable-Hair#3]

**Comment by Xiaojiu-z** [comment]
你好👋，感谢你的提问，bald converter的训练，使用的是HairMapper团队公开的non-hair FFHQ数据集，因此呈现效果与hairmapper类似会有边界模糊，但相比于hairmapper，我们的方法不需要脸部对齐以及inversion，适用于in-the-wild人脸数据。另外，代码和demo正在完善中～

**Comment by Dratlan** [comment]
请问对于解决non-hair FFHQ数据集中光头边界模糊效果有没有什么好方法

**Comment by Xiaojiu-z** [comment]
> 请问对于解决non-hair FFHQ数据集中光头边界模糊效果有没有什么好方法

我放出的model使用了random背景的策略，把光头和目标图像mask出来，贴到同一个新的背景下，这个训练方式有助于抵消光头边界的模糊。
