### ISSUE TITLE
About the latent controlnet

### ISSUE THREAD

**Issue by YangPanHZAU** [Xiaojiu-z/Stable-Hair#8]
@Xiaojiu-z 
Thanks for your great work! My research interests are very similar to yours. I try to solve color deviation by reproducing the Latent controlnet structure according to the paper. 

```
class Latent_ControlNetConditioningEmbedding(nn.Module):
    """
    input is the latent condition, there is no need to downsample the input latent image
    """

    def __init__(
        self,
        conditioning_embedding_channels: int,
        conditioning_channels: int = 4,
    ):
        super().__init__()
        self.conv_out = zero_module(
            nn.Conv2d(conditioning_channels, conditioning_embedding_channels, kernel_size=3, padding=1)
        )

    def forward(self, conditioning):
        embedding = self.conv_out(conditioning)
        return embedding
```
I think the raw **ControlNetConditioningEmbedding** in diffusers can be replaced with the aboved **Latent_ControlNetConditioningEmbedding**.
is it implemented in this way in the **_Stablehair_**?

Looking forward to your reply.

**Comment by Xiaojiu-z** [comment]
> @Xiaojiu-z Thanks for your great work! My research interests are very similar to yours. I try to solve color deviation by reproducing the Latent controlnet structure according to the paper.
> 
> ```
> class Latent_ControlNetConditioningEmbedding(nn.Module):
>     """
>     input is the latent condition, there is no need to downsample the input latent image
>     """
> 
>     def __init__(
>         self,
>         conditioning_embedding_channels: int,
>         conditioning_channels: int = 4,
>     ):
>         super().__init__()
>         self.conv_out = zero_module(
>             nn.Conv2d(conditioning_channels, conditioning_embedding_channels, kernel_size=3, padding=1)
>         )
> 
>     def forward(self, conditioning):
>         embedding = self.conv_out(conditioning)
>         return embedding
> ```
> 
> I think the raw **ControlNetConditioningEmbedding** in diffusers can be replaced with the aboved **Latent_ControlNetConditioningEmbedding**. is it implemented in this way in the **_Stablehair_**?
> 
> Looking forward to your reply.

yeah~ and you need to add a new conv_in to encode the inputs
```
# input
        conv_in_kernel = 3
        conv_in_padding = (conv_in_kernel - 1) // 2
        self.conv_in = nn.Conv2d(
            in_channels, block_out_channels[0], kernel_size=conv_in_kernel, padding=conv_in_padding
        )
        self.newly_added_conv_in = nn.Conv2d(
            in_channels, block_out_channels[0], kernel_size=conv_in_kernel, padding=conv_in_padding
        )

# forward
sample = self.conv_in(sample)
controlnet_cond = self.newly_added_conv_in(controlnet_latent_cond)
sample = sample + controlnet_cond

```
